
#include "tz_xref.h"
/***************************************************
 * Array of these structs provides the mapping between
 * Microsoft TZID or "TZID display name" to a POSIX
 * timezone. If you encounter a TZID not listed here,
 * please add in the correct mapping.
 *
 * Mon Jun 28 17:59:13 EDT 2021
 * Sourced from https://github.com/unicode-org/cldr/blob/master/common/supplemental/windowsZones.xml
 * NOTE: Windows has fewer timezones than POSIX, so the one-to-one mapping here is just my guess as 
 * to the likely POSIX timezone.
 */
struct tz_xref Ms2Posix[]= {
   /* Make sure to supply a sufficiently unique string to match what immediately
    * follows 'TZID=', or 'DTSTAMP' (no colon).
    */
//   {.ms= "\"(UTC-06:00) Central Time (US & Canada)\"", .posix= "America/Chicago" },
//   {.ms= "Central Standard Time:", .posix= "America/Chicago" },
//   {.ms= "Eastern Standard Time:", .posix= "America/New_York" },
   {.ms= "\"(UTC-12:00) International Date Line West\"", .posix= "Etc/GMT+12"}, 
   {.ms= "Dateline Standard Time:", .posix=  "Etc/GMT+12"},
   {.ms= "\"(UTC-11:00) Coordinated Universal Time-11\"", .posix= "Etc/GMT+11"},
   {.ms= "UTC-11:", .posix= "Etc/GMT+11"},
   {.ms= "\"(UTC-10:00) Aleutian Islands\"", .posix= "America/Adak"}, 
   {.ms= "Aleutian Standard Time:", .posix= "America/Adak"},
   {.ms= "\"(UTC-10:00) Hawaii\"", .posix= "Pacific/Honolulu"}, 
   {.ms= "Hawaiian Standard Time:", .posix= "Pacific/Honolulu"},
   {.ms= "\"(UTC-09:30) Marquesas Islands\"", .posix= "Pacific/Marquesas"}, 
   {.ms= "Marquesas Standard Time:", .posix= "Pacific/Marquesas"},
   {.ms= "\"(UTC-09:00) Alaska\"", .posix= "America/Anchorage"}, 
   {.ms= "Alaskan Standard Time:", .posix= "America/Anchorage"},
   {.ms= "\"(UTC-09:00) Coordinated Universal Time-09\"", .posix= "Etc/GMT+9"}, 
   {.ms= "UTC-09:", .posix= "Etc/GMT+9"},
   {.ms= "\"(UTC-08:00) Baja California\"", .posix= "America/Tijuana"}, 
   {.ms= "Pacific Standard Time (Mexico):", .posix= "America/Tijuana"},
   {.ms= "\"(UTC-08:00) Coordinated Universal Time-08\"", .posix= "Etc/GMT+8"}, 
   {.ms= "UTC-08:", .posix= "Etc/GMT+8"},
   {.ms= "\"(UTC-08:00) Pacific Time (US & Canada)\"", .posix= "America/Los_Angeles"}, 
   {.ms= "Pacific Standard Time:", .posix= "America/Los_Angeles"},
   {.ms= "\"(UTC-07:00) Arizona\"", .posix= "America/Phoenix"}, 
   {.ms= "US Mountain Standard Time:", .posix= "America/Phoenix"},
   {.ms= "\"(UTC-07:00) Chihuahua, La Paz, Mazatlan\"", .posix= "America/Chihuahua"}, 
   {.ms= "Mountain Standard Time (Mexico):", .posix= "America/Chihuahua"},
   {.ms= "\"(UTC-07:00) Mountain Time (US & Canada)\"", .posix= "America/Denver"}, 
   {.ms= "Mountain Standard Time:", .posix= "America/Denver"},
   {.ms= "\"(UTC-07:00) Yukon\"", .posix= "America/Whitehorse"}, 
   {.ms= "Yukon Standard Time:", .posix= "America/Whitehorse"},
   {.ms= "\"(UTC-06:00) Central America\"", .posix= "America/Costa_Rica"}, 
   {.ms= "Central America Standard Time:", .posix= "America/Costa_Rica"},
   {.ms= "\"(UTC-06:00) Central Time (US & Canada)\"", .posix= "America/Chicago" }, 
   {.ms= "Central Standard Time:", .posix= "America/Chicago" },
   {.ms= "\"(UTC-06:00) Easter Island\"", .posix= "Pacific/Easter"}, 
   {.ms= "Easter Island Standard Time:", .posix= "Pacific/Easter"},
   {.ms= "\"(UTC-06:00) Guadalajara, Mexico City, Monterrey\"", .posix= "America/Mexico_City"}, 
   {.ms= "Central Standard Time (Mexico):", .posix= "America/Mexico_City"},
   {.ms= "\"(UTC-06:00) Saskatchewan\"", .posix= "America/Regina"}, 
   {.ms= "Canada Central Standard Time:", .posix= "America/Regina"},
   {.ms= "\"(UTC-05:00) Bogota, Lima, Quito, Rio Branco\"", .posix= "America/Bogota"}, 
   {.ms= "SA Pacific Standard Time:", .posix= "America/Bogota"},
   {.ms= "\"(UTC-05:00) Chetumal\"", .posix= "America/Cancun"}, 
   {.ms= "Eastern Standard Time (Mexico):", .posix= "America/Cancun"},
   {.ms= "\"(UTC-05:00) Eastern Time (US & Canada)\"", .posix= "America/New_York"}, 
   {.ms= "Eastern Standard Time:", .posix= "America/New_York"},
   {.ms= "\"(UTC-05:00) Haiti\"", .posix= "America/Port-au-Prince"}, 
   {.ms= "Haiti Standard Time:", .posix= "America/Port-au-Prince"},
   {.ms= "\"(UTC-05:00) Havana\"", .posix= "America/Havana"}, 
   {.ms= "Cuba Standard Time:", .posix= "America/Havana"},
   {.ms= "\"(UTC-05:00) Indiana (East)\"", .posix= "America/Indianapolis"}, 
   {.ms= "US Eastern Standard Time:", .posix= "America/Indianapolis"},
   {.ms= "\"(UTC-05:00) Turks and Caicos\"", .posix= "America/Grand_Turk"}, 
   {.ms= "Turks And Caicos Standard Time:", .posix= "America/Grand_Turk"},
   {.ms= "\"(UTC-04:00) Asuncion\"", .posix= "America/Asuncion"}, 
   {.ms= "Paraguay Standard Time:", .posix= "America/Asuncion"},
   {.ms= "\"(UTC-04:00) Atlantic Time (Canada)\"", .posix= "America/Halifax"}, 
   {.ms= "Atlantic Standard Time:", .posix= "America/Halifax"},
   {.ms= "\"(UTC-04:00) Caracas\"", .posix= "America/Caracas"}, 
   {.ms= "Venezuela Standard Time:", .posix= "America/Caracas"},
   {.ms= "\"(UTC-04:00) Cuiaba\"", .posix= "America/Cuiaba"}, 
   {.ms= "Central Brazilian Standard Time:", .posix= "America/Cuiaba"},
   {.ms= "\"(UTC-04:00) Georgetown, La Paz, Manaus, San Juan\"", .posix= "America/La_Paz"}, 
   {.ms= "SA Western Standard Time:", .posix= "America/La_Paz"},
   {.ms= "\"(UTC-04:00) Santiago\"", .posix= "America/Santiago"}, 
   {.ms= "Pacific SA Standard Time:", .posix= "America/Santiago"},
   {.ms= "\"(UTC-03:30) Newfoundland\"", .posix= "America/St_Johns"}, 
   {.ms= "Newfoundland Standard Time:", .posix= "America/St_Johns"},
   {.ms= "\"(UTC-03:00) Araguaina\"", .posix= "America/Araguaina"}, 
   {.ms= "Tocantins Standard Time:", .posix= "America/Araguaina"},
   {.ms= "\"(UTC-03:00) Brasilia\"", .posix= "America/Sao_Paulo"}, 
   {.ms= "E. South America Standard Time:", .posix= "America/Sao_Paulo"},
   {.ms= "\"(UTC-03:00) Cayenne, Fortaleza\"", .posix= "America/Fortaleza"}, 
   {.ms= "SA Eastern Standard Time:", .posix= "America/Fortaleza"},
   {.ms= "\"(UTC-03:00) City of Buenos Aires\"", .posix= "America/Buenos_Aires"}, 
   {.ms= "Argentina Standard Time:", .posix= "America/Buenos_Aires"},
   {.ms= "\"(UTC-03:00) Greenland\"", .posix= "America/Godthab"}, 
   {.ms= "Greenland Standard Time:", .posix= "America/Godthab"},
   {.ms= "\"(UTC-03:00) Montevideo\"", .posix= "America/Montevideo"}, 
   {.ms= "Montevideo Standard Time:", .posix= "America/Montevideo"},
   {.ms= "\"(UTC-03:00) Punta Arenas\"", .posix= "America/Punta_Arenas"}, 
   {.ms= "Magallanes Standard Time:", .posix= "America/Punta_Arenas"},
   {.ms= "\"(UTC-03:00) Saint Pierre and Miquelon\"", .posix= "America/Miquelon"}, 
   {.ms= "Saint Pierre Standard Time:", .posix= "America/Miquelon"},
   {.ms= "\"(UTC-03:00) Salvador\"", .posix= "America/Bahia"}, 
   {.ms= "Bahia Standard Time:", .posix= "America/Bahia"},
   {.ms= "\"(UTC-02:00) Coordinated Universal Time-02\"", .posix= "Etc/GMT+2"}, 
   {.ms= "UTC-02:", .posix= "Etc/GMT+2"},
   {.ms= "\"(UTC-01:00) Azores\"", .posix= "Atlantic/Azores"}, 
   {.ms= "Azores Standard Time:", .posix= "Atlantic/Azores"},
   {.ms= "\"(UTC-01:00) Cabo Verde Is.\"", .posix= "Atlantic/Cape_Verde"}, 
   {.ms= "Cape Verde Standard Time:", .posix= "Atlantic/Cape_Verde"},
   {.ms= "\"(UTC) Coordinated Universal Time\"", .posix= "Etc/UTC"}, 
   {.ms= "UTC:", .posix= "Etc/UTC"},
   {.ms= "\"(UTC+00:00) Dublin, Edinburgh, Lisbon, London\"", .posix= "Europe/London"}, 
   {.ms= "GMT Standard Time:", .posix= "Europe/London"},
   {.ms= "\"(UTC+00:00) Monrovia, Reykjavik\"", .posix= "Atlantic/Reykjavik"}, 
   {.ms= "Greenwich Standard Time:", .posix= "Atlantic/Reykjavik"},
   {.ms= "\"(UTC+00:00) Sao Tome\"", .posix= "Africa/Sao_Tome"}, 
   {.ms= "Sao Tome Standard Time:", .posix= "Africa/Sao_Tome"},
   {.ms= "\"(UTC+01:00) Casablanca\"", .posix= "Africa/Casablanca"}, 
   {.ms= "Morocco Standard Time:", .posix= "Africa/Casablanca"},
   {.ms= "\"(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna\"", .posix= "Europe/Amsterdam"}, 
   {.ms= "W. Europe Standard Time:", .posix= "Europe/Amsterdam"},
   {.ms= "\"(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague\"", .posix= "Europe/Budapest"}, 
   {.ms= "Central Europe Standard Time:", .posix= "Europe/Budapest"},
   {.ms= "\"(UTC+01:00) Brussels, Copenhagen, Madrid, Paris\"", .posix= "Europe/Paris"}, 
   {.ms= "Romance Standard Time:", .posix= "Europe/Paris"},
   {.ms= "\"(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb\"", .posix= "Europe/Sarajevo"}, 
   {.ms= "Central European Standard Time:", .posix= "Europe/Sarajevo"},
   {.ms= "\"(UTC+01:00) West Central Africa\"", .posix= "Africa/Lagos"}, 
   {.ms= "W. Central Africa Standard Time:", .posix= "Africa/Lagos"},
   {.ms= "\"(UTC+02:00) Amman\"", .posix= "Asia/Amman"}, 
   {.ms= "Jordan Standard Time:", .posix= "Asia/Amman"},
   {.ms= "\"(UTC+02:00) Athens, Bucharest\"", .posix= "Europe/Bucharest"}, 
   {.ms= "GTB Standard Time:", .posix= "Europe/Bucharest"},
   {.ms= "\"(UTC+02:00) Beirut\"", .posix= "Asia/Beirut"}, 
   {.ms= "Middle East Standard Time:", .posix= "Asia/Beirut"},
   {.ms= "\"(UTC+02:00) Cairo\"", .posix= "Africa/Cairo"}, 
   {.ms= "Egypt Standard Time:", .posix= "Africa/Cairo"},
   {.ms= "\"(UTC+02:00) Chisinau\"", .posix= "Europe/Chisinau"}, 
   {.ms= "E. Europe Standard Time:", .posix= "Europe/Chisinau"},
   {.ms= "\"(UTC+02:00) Damascus\"", .posix= "Asia/Damascus"}, 
   {.ms= "Syria Standard Time:", .posix= "Asia/Damascus"},
   {.ms= "\"(UTC+02:00) Gaza, Hebron\"", .posix= "Asia/Hebron"}, 
   {.ms= "West Bank Standard Time:", .posix= "Asia/Hebron"},
   {.ms= "\"(UTC+02:00) Harare, Pretoria\"", .posix= "Africa/Johannesburg"}, 
   {.ms= "South Africa Standard Time:", .posix= "Africa/Johannesburg"},
   {.ms= "\"(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius\"", .posix= "Europe/Kiev"}, 
   {.ms= "FLE Standard Time:", .posix= "Europe/Kiev"},
   {.ms= "\"(UTC+02:00) Jerusalem\"", .posix= "Asia/Jerusalem"}, 
   {.ms= "Israel Standard Time:", .posix= "Asia/Jerusalem"},
   {.ms= "\"(UTC+02:00) Juba\"", .posix= "Africa/Juba"}, 
   {.ms= "South Sudan Standard Time:", .posix= "Africa/Juba"},
   {.ms= "\"(UTC+02:00) Kaliningrad\"", .posix= "Europe/Kaliningrad"}, 
   {.ms= "Kaliningrad Standard Time:", .posix= "Europe/Kaliningrad"},
   {.ms= "\"(UTC+02:00) Khartoum\"", .posix= "Africa/Khartoum"}, 
   {.ms= "Sudan Standard Time:", .posix= "Africa/Khartoum"},
   {.ms= "\"(UTC+02:00) Tripoli\"", .posix= "Africa/Tripoli"}, 
   {.ms= "Libya Standard Time:", .posix= "Africa/Tripoli"},
   {.ms= "\"(UTC+02:00) Windhoek\"", .posix= "Africa/Windhoek"}, 
   {.ms= "Namibia Standard Time:", .posix= "Africa/Windhoek"},
   {.ms= "\"(UTC+03:00) Baghdad\"", .posix= "Asia/Baghdad"}, 
   {.ms= "Arabic Standard Time:", .posix= "Asia/Baghdad"},
   {.ms= "\"(UTC+03:00) Istanbul\"", .posix= "Europe/Istanbul"}, 
   {.ms= "Turkey Standard Time:", .posix= "Europe/Istanbul"},
   {.ms= "\"(UTC+03:00) Kuwait, Riyadh\"", .posix= "Asia/Riyadh"}, 
   {.ms= "Arab Standard Time:", .posix= "Asia/Riyadh"},
   {.ms= "\"(UTC+03:00) Minsk\"", .posix= "Europe/Minsk"}, 
   {.ms= "Belarus Standard Time:", .posix= "Europe/Minsk"},
   {.ms= "\"(UTC+03:00) Moscow, St. Petersburg\"", .posix= "Europe/Moscow"}, 
   {.ms= "Russian Standard Time:", .posix= "Europe/Moscow"},
   {.ms= "\"(UTC+03:00) Nairobi\"", .posix= "Africa/Nairobi"}, 
   {.ms= "E. Africa Standard Time:", .posix= "Africa/Nairobi"},
   {.ms= "\"(UTC+03:00) Volgograd\"", .posix= "Europe/Volgograd"}, 
   {.ms= "Volgograd Standard Time:", .posix= "Europe/Volgograd"},
   {.ms= "\"(UTC+03:30) Tehran\"", .posix= "Asia/Tehran"}, 
   {.ms= "Iran Standard Time:", .posix= "Asia/Tehran"},
   {.ms= "\"(UTC+04:00) Abu Dhabi, Muscat\"", .posix= "Asia/Dubai"}, 
   {.ms= "Arabian Standard Time:", .posix= "Asia/Dubai"},
   {.ms= "\"(UTC+04:00) Astrakhan, Ulyanovsk\"", .posix= "Europe/Astrakhan"}, 
   {.ms= "Astrakhan Standard Time:", .posix= "Europe/Astrakhan"},
   {.ms= "\"(UTC+04:00) Baku\"", .posix= "Asia/Baku"}, 
   {.ms= "Azerbaijan Standard Time:", .posix= "Asia/Baku"},
   {.ms= "\"(UTC+04:00) Izhevsk, Samara\"", .posix= "Europe/Samara"}, 
   {.ms= "Russia Time Zone 3:", .posix= "Europe/Samara"},
   {.ms= "\"(UTC+04:00) Port Louis\"", .posix= "Indian/Mauritius"}, 
   {.ms= "Mauritius Standard Time:", .posix= "Indian/Mauritius"},
   {.ms= "\"(UTC+04:00) Saratov\"", .posix= "Europe/Saratov"}, 
   {.ms= "Saratov Standard Time:", .posix= "Europe/Saratov"},
   {.ms= "\"(UTC+04:00) Tbilisi\"", .posix= "Asia/Tbilisi"}, 
   {.ms= "Georgian Standard Time:", .posix= "Asia/Tbilisi"},
   {.ms= "\"(UTC+04:00) Yerevan\"", .posix= "Asia/Yerevan"}, 
   {.ms= "Caucasus Standard Time:", .posix= "Asia/Yerevan"},
   {.ms= "\"(UTC+04:30) Kabul\"", .posix= "Asia/Kabul"}, 
   {.ms= "Afghanistan Standard Time:", .posix= "Asia/Kabul"},
   {.ms= "\"(UTC+05:00) Ashgabat, Tashkent\"", .posix= "Asia/Tashkent"}, 
   {.ms= "West Asia Standard Time:", .posix= "Asia/Tashkent"},
   {.ms= "\"(UTC+05:00) Ekaterinburg\"", .posix= "Asia/Yekaterinburg"}, 
   {.ms= "Ekaterinburg Standard Time:", .posix= "Asia/Yekaterinburg"},
   {.ms= "\"(UTC+05:00) Islamabad, Karachi\"", .posix= "Asia/Karachi"}, 
   {.ms= "Pakistan Standard Time:", .posix= "Asia/Karachi"},
   {.ms= "\"(UTC+05:00) Qyzylorda\"", .posix= "Asia/Qyzylorda"}, 
   {.ms= "Qyzylorda Standard Time:", .posix= "Asia/Qyzylorda"},
   {.ms= "\"(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi\"", .posix= "Asia/Calcutta"}, 
   {.ms= "India Standard Time:", .posix= "Asia/Calcutta"},
   {.ms= "\"(UTC+05:30) Sri Jayawardenepura\"", .posix= "Asia/Colombo"}, 
   {.ms= "Sri Lanka Standard Time:", .posix= "Asia/Colombo"},
   {.ms= "\"(UTC+05:45) Kathmandu\"", .posix= "Asia/Katmandu"}, 
   {.ms= "Nepal Standard Time:", .posix= "Asia/Katmandu"},
   {.ms= "\"(UTC+06:00) Astana\"", .posix= "Asia/Almaty"}, 
   {.ms= "Central Asia Standard Time:", .posix= "Asia/Almaty"},
   {.ms= "\"(UTC+06:00) Dhaka\"", .posix= "Asia/Dhaka"}, 
   {.ms= "Bangladesh Standard Time:", .posix= "Asia/Dhaka"},
   {.ms= "\"(UTC+06:00) Omsk\"", .posix= "Asia/Omsk"}, 
   {.ms= "Omsk Standard Time:", .posix= "Asia/Omsk"},
   {.ms= "\"(UTC+06:30) Yangon (Rangoon)\"", .posix= "Asia/Rangoon"}, 
   {.ms= "Myanmar Standard Time:", .posix= "Asia/Rangoon"},
   {.ms= "\"(UTC+07:00) Bangkok, Hanoi, Jakarta\"", .posix= "Asia/Bangkok"}, 
   {.ms= "SE Asia Standard Time:", .posix= "Asia/Bangkok"},
   {.ms= "\"(UTC+07:00) Barnaul, Gorno-Altaysk\"", .posix= "Asia/Barnaul"}, 
   {.ms= "Altai Standard Time:", .posix= "Asia/Barnaul"},
   {.ms= "\"(UTC+07:00) Hovd\"", .posix= "Asia/Hovd"}, 
   {.ms= "W. Mongolia Standard Time:", .posix= "Asia/Hovd"},
   {.ms= "\"(UTC+07:00) Krasnoyarsk\"", .posix= "Asia/Krasnoyarsk"}, 
   {.ms= "North Asia Standard Time:", .posix= "Asia/Krasnoyarsk"},
   {.ms= "\"(UTC+07:00) Novosibirsk\"", .posix= "Asia/Novosibirsk"}, 
   {.ms= "N. Central Asia Standard Time:", .posix= "Asia/Novosibirsk"},
   {.ms= "\"(UTC+07:00) Tomsk\"", .posix= "Asia/Tomsk"}, 
   {.ms= "Tomsk Standard Time:", .posix= "Asia/Tomsk"},
   {.ms= "\"(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi\"", .posix= "Asia/Shanghai"}, 
   {.ms= "China Standard Time:", .posix= "Asia/Shanghai"},
   {.ms= "\"(UTC+08:00) Irkutsk\"", .posix= "Asia/Irkutsk"}, 
   {.ms= "North Asia East Standard Time:", .posix= "Asia/Irkutsk"},
   {.ms= "\"(UTC+08:00) Kuala Lumpur, Singapore\"", .posix= "Asia/Singapore"}, 
   {.ms= "Singapore Standard Time:", .posix= "Asia/Singapore"},
   {.ms= "\"(UTC+08:00) Perth\"", .posix= "Australia/Perth"}, 
   {.ms= "W. Australia Standard Time:", .posix= "Australia/Perth"},
   {.ms= "\"(UTC+08:00) Taipei\"", .posix= "Asia/Taipei"}, 
   {.ms= "Taipei Standard Time:", .posix= "Asia/Taipei"},
   {.ms= "\"(UTC+08:00) Ulaanbaatar\"", .posix= "Asia/Ulaanbaatar"}, 
   {.ms= "Ulaanbaatar Standard Time:", .posix= "Asia/Ulaanbaatar"},
   {.ms= "\"(UTC+08:45) Eucla\"", .posix= "Australia/Eucla"}, 
   {.ms= "Aus Central W. Standard Time:", .posix= "Australia/Eucla"},
   {.ms= "\"(UTC+09:00) Chita\"", .posix= "Asia/Chita"}, 
   {.ms= "Transbaikal Standard Time:", .posix= "Asia/Chita"},
   {.ms= "\"(UTC+09:00) Osaka, Sapporo, Tokyo\"", .posix= "Asia/Tokyo"}, 
   {.ms= "Tokyo Standard Time:", .posix= "Asia/Tokyo"},
   {.ms= "\"(UTC+09:00) Pyongyang\"", .posix= "Asia/Pyongyang"}, 
   {.ms= "North Korea Standard Time:", .posix= "Asia/Pyongyang"},
   {.ms= "\"(UTC+09:00) Seoul\"", .posix= "Asia/Seoul"}, 
   {.ms= "Korea Standard Time:", .posix= "Asia/Seoul"},
   {.ms= "\"(UTC+09:00) Yakutsk\"", .posix= "Asia/Yakutsk"}, 
   {.ms= "Yakutsk Standard Time:", .posix= "Asia/Yakutsk"},
   {.ms= "\"(UTC+09:30) Adelaide\"", .posix= "Australia/Adelaide"}, 
   {.ms= "Cen. Australia Standard Time:", .posix= "Australia/Adelaide"},
   {.ms= "\"(UTC+09:30) Darwin\"", .posix= "Australia/Darwin"}, 
   {.ms= "AUS Central Standard Time:", .posix= "Australia/Darwin"},
   {.ms= "\"(UTC+10:00) Brisbane\"", .posix= "Australia/Brisbane"}, 
   {.ms= "E. Australia Standard Time:", .posix= "Australia/Brisbane"},
   {.ms= "\"(UTC+10:00) Canberra, Melbourne, Sydney\"", .posix= "Australia/Sydney"}, 
   {.ms= "AUS Eastern Standard Time:", .posix= "Australia/Sydney"},
   {.ms= "\"(UTC+10:00) Guam, Port Moresby\"", .posix= "Pacific/Port_Moresby"}, 
   {.ms= "West Pacific Standard Time:", .posix= "Pacific/Port_Moresby"},
   {.ms= "\"(UTC+10:00) Hobart\"", .posix= "Australia/Hobart"}, 
   {.ms= "Tasmania Standard Time:", .posix= "Australia/Hobart"},
   {.ms= "\"(UTC+10:00) Vladivostok\"", .posix= "Asia/Vladivostok"}, 
   {.ms= "Vladivostok Standard Time:", .posix= "Asia/Vladivostok"},
   {.ms= "\"(UTC+10:30) Lord Howe Island\"", .posix= "Australia/Lord_Howe"}, 
   {.ms= "Lord Howe Standard Time:", .posix= "Australia/Lord_Howe"},
   {.ms= "\"(UTC+11:00) Bougainville Island\"", .posix= "Pacific/Bougainville"}, 
   {.ms= "Bougainville Standard Time:", .posix= "Pacific/Bougainville"},
   {.ms= "\"(UTC+11:00) Chokurdakh\"", .posix= "Asia/Srednekolymsk"}, 
   {.ms= "Russia Time Zone 10:", .posix= "Asia/Srednekolymsk"},
   {.ms= "\"(UTC+11:00) Magadan\"", .posix= "Asia/Magadan"}, 
   {.ms= "Magadan Standard Time:", .posix= "Asia/Magadan"},
   {.ms= "\"(UTC+11:00) Norfolk Island\"", .posix= "Pacific/Norfolk"}, 
   {.ms= "Norfolk Standard Time:", .posix= "Pacific/Norfolk"},
   {.ms= "\"(UTC+11:00) Sakhalin\"", .posix= "Asia/Sakhalin"}, 
   {.ms= "Sakhalin Standard Time:", .posix= "Asia/Sakhalin"},
   {.ms= "\"(UTC+11:00) Solomon Is., New Caledonia\"", .posix= "Pacific/Guadalcanal"}, 
   {.ms= "Central Pacific Standard Time:", .posix= "Pacific/Guadalcanal"},
   {.ms= "\"(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky\"", .posix= "Asia/Kamchatka"}, 
   {.ms= "Russia Time Zone 11:", .posix= "Asia/Kamchatka"},
   {.ms= "\"(UTC+12:00) Auckland, Wellington\"", .posix= "Pacific/Auckland"}, 
   {.ms= "New Zealand Standard Time:", .posix= "Pacific/Auckland"},
   {.ms= "\"(UTC+12:00) Coordinated Universal Time+12\"", .posix= "Etc/GMT-12"}, 
   {.ms= "UTC+12:", .posix= "Etc/GMT-12"},
   {.ms= "\"(UTC+12:00) Fiji\"", .posix= "Pacific/Fiji"}, 
   {.ms= "Fiji Standard Time:", .posix= "Pacific/Fiji"},
   {.ms= "\"(UTC+12:45) Chatham Islands\"", .posix= "Pacific/Chatham"}, 
   {.ms= "Chatham Islands Standard Time:", .posix= "Pacific/Chatham"},
   {.ms= "\"(UTC+13:00) Coordinated Universal Time+13\"", .posix= "Etc/GMT-13"}, 
   {.ms= "UTC+13:", .posix= "Etc/GMT-13"},
   {.ms= "\"(UTC+13:00) Nuku'alofa\"", .posix= "Pacific/Tongatapu"}, 
   {.ms= "Tonga Standard Time:", .posix= "Pacific/Tongatapu"},
   {.ms= "\"(UTC+13:00) Samoa\"", .posix= "Pacific/Apia"}, 
   {.ms= "Samoa Standard Time:", .posix= "Pacific/Apia"},
   {.ms= "\"(UTC+14:00) Kiritimati Island\"", .posix= "Pacific/Kiritimati"}, 
   {.ms= "Line Islands Standard Time:", .posix= "Pacific/Kiritimati"},
   /*--- >>> LOOK <<< Add other members here ---*/
   { /* Terminating member */ }
};
